export const GET_USER_REQUEST = "GET_USER_REQUEST" 
export const GET_USER_SUCCESS = "GET_USER_SUCCESS" 
export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const GET_ALL_COURSES_REQUEST = "GET_ALL_COURSES_REQUEST" 
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS" 
export const GET_ALL_COURSES_FAILURE = "GET_ALL_COURSES_FAILURE" 

export const TOGGLE_CLICK = "TOGGLE_CLICK"